---
- name: create GCP instance
  hosts: localhost
  
  tasks:   
    - name: create a disk
      gcp_compute_disk:
        name: "{{ gcp_disk_instance }}"
        size_gb: 20
        source_image: projects/centos-cloud/global/images/family/centos-8
        zone: us-central1-a
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: disk

    - name: create a address
      gcp_compute_address:
        name: "{{ gcp_address_instance }}"
        region: us-central1
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: address
    - name: create a instance
      gcp_compute_instance:
        name: "{{ gcp_compute_instance }}"
        machine_type: f1-micro
        disks:
        - auto_delete: 'true'
          boot: 'true'
          source: "{{ disk }}"
        labels:
          environment: production
        network_interfaces:
        - network: null
          access_configs:
          - name: External NAT
            type: ONE_TO_ONE_NAT
            nat_ip: "{{ address }}"
        zone: us-central1-a
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
    - name: Show vm address
      debug: 
        msg: "Address is {{ address.address }}"

    - name: Wait for SSH to come up
      wait_for: host={{ address.address }} port=22 delay=10 timeout=180 state=started

    - name: Add host to groupname
      add_host: hostname={{ address.address }} groupname=new_instances

    - name: Install httpd
      become: yes
      yum:
        name: httpd
        state: present  

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes    

    - name: Install docker
      become: yes
      package :
        name: docker-ce
        state: latest
      
    - name: Install dependencies
      become: yes
      yum:
        name: "{{ item }}"  
        state: present
      loop: 
         - yum-utils
    

    - name: Start docker
      become: yes
      service:
        name: docker
        state: started
        enabled: yes

    - name: installing docker SDK
      command: "pip3 install docker"    

    - name: Start Application
      become: yes
      command: "docker run --rm --name javaapplication sakshikansal/maven-sample-application:latest"
